FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py init_db.py ./
COPY templates/ templates/
COPY ../scripts/run.sh ./

RUN chmod +x run.sh

EXPOSE 5000
CMD ["./run.sh"]
